##
# Test Solidjs Project
##

name: Build Project

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Setup node and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - run: npm install -g pnpm

      - name: Build project
        run: |
          pnpm install
          npm run build
